### ISSUE TITLE
o1-preview가 2025 SAT에서 뭐 틀린건가요?

### ISSUE THREAD

**Issue by min99830** [Marker-Inc-Korea/Korean-SAT-LLM-Leaderboard#16]
이쯤되니 어느 문제를 틀린건지도 궁금하네요.

**Comment by minsing-jin** [comment]
@min99830 수능 LLM 리더보드 벤치마크에 많은 관심을 가져주셔서 감사드립니다!  o1-preview가 틀린 문제는 8번(3점) 비문학지문이었습니다. 

정답은 1번이었지만 o1-preview가 선택한 답은은 3번이었습니다. 재밌는 사실은 한국 수험생 또한 [8번 오답률이 81.5%](https://www.ebsi.co.kr/ebs/xip/xipa/retrievePastGrdCutWrongAnswerRate.ebs?tab=1)로 가장 어려워했네요.

[실험과정 정리 블로그](https://velog.io/@minsing-jin/o1-preview-2025-%EC%88%98%EB%8A%A5-%EA%B5%AD%EC%96%B4-97%EC%A0%90-%EB%8B%AC%EC%84%B1)
